"""
Opaque bearer/handoff token generation and storage-hashing (Phase 21).

Shared by two Phase 21 concerns that both need the exact same security
property -- "a cryptographically random, single-use, storable-without-
exposing-the-secret token": authenticated-session bearer tokens
(`app.core.auth_manager`) and QR custody-handoff tokens
(`app.core.custody_manager`). One implementation, reused by both, rather
than two ad hoc token schemes.

Reuses `app.hashing.sha256.sha256_bytes` (Phase 3/16's own SHA-256
primitive) to compute the *storage* hash of a token -- never a second
SHA-256 implementation. This is a different use of SHA-256 than
`app.security.passwords` deliberately avoids for passwords: a token
generated by `generate_token` already has 256 bits of real entropy (via
`secrets.token_urlsafe`), so it is not guessable/brute-forceable the way
a human-chosen password is, making a fast, unsalted hash the *correct*
choice here (the same reasoning Phase 16's audit-chain hashing and Phase
3's evidence hashing already rely on) -- unlike a password, there is no
weak-secret risk a slow hash would need to compensate for.
"""

from __future__ import annotations

import secrets

from app.hashing.sha256 import sha256_bytes

__all__ = ["TOKEN_BYTES", "generate_token", "hash_token"]

#: 32 random bytes (256 bits) before URL-safe base64 encoding -- the same
#: entropy budget `secrets` itself recommends for security-sensitive
#: tokens.
TOKEN_BYTES = 32


def generate_token() -> str:
    """Generate a new cryptographically random opaque token.

    Returns:
        A URL-safe, printable token string. Never persisted directly
        anywhere -- callers store only `hash_token(token)` and return the
        raw value to the caller exactly once.
    """
    return secrets.token_urlsafe(TOKEN_BYTES)


def hash_token(raw_token: str) -> str:
    """Compute the storage representation of a raw token.

    Args:
        raw_token: The raw token value (from `generate_token`, or
            supplied by a caller presenting a previously-issued token).

    Returns:
        The lowercase hex SHA-256 digest of the token's UTF-8 bytes --
        this is what gets stored/compared in the database, never the raw
        token itself (task Phase 21 scope section 10: "Store only a
        secure representation/hash of the token if practical").
    """
    return sha256_bytes(raw_token.encode("utf-8"))
