"""phase_21_custody_auth

Revision ID: 074a6657727b
Revises: da8531b249c6
Create Date: 2026-08-30 17:51:22.675638

Adds the three tables Phase 21 ("Physical Chain of Custody + QR Handoff")
needs. None of this touches any Phase 1-20 table -- `evidence`, `jobs`,
`processing_events`, etc. are read via foreign key only.

- `users` (`app/models/user.py`): authenticated human principals
  (officer / lab personnel / admin). New -- no prior authentication
  system existed anywhere in this codebase (see that module's own
  "Authentication Gap Assessment" docstring section for the exhaustive
  inspection that established this).
- `user_sessions` (`app/models/auth_session.py`): short-lived bearer
  sessions issued at login. Stores only `token_hash` (SHA-256 of the
  raw token) -- the raw token itself is never persisted.
- `custody_transfers` (`app/models/custody.py`): one row per physical
  custody event -- either the initial intake of an evidence item into
  tracked custody (`transfer_type='intake'`, created already
  `status='accepted'`) or a person-to-person QR handoff
  (`transfer_type='transfer'`, `status` starts `'pending'` and moves to
  exactly one terminal value). `token_hash` stores only the SHA-256 of
  the opaque QR token, never the raw token. There is deliberately no
  `current_custodian` column anywhere -- `app.core.custody_manager.
  CustodyManager.get_current_custodian` derives it from this table's own
  history (latest `accepted` row) on every call, per the task's explicit
  "source of truth: custody history, never a cached field" requirement.
  `provenance_event_id` links a completed transfer to the single Phase 15
  `ProcessingEvent` recorded for it (nullable -- `NULL` until the
  transfer completes, and permanently for one that never does).

Autogenerated from `app/models/{user,auth_session,custody}.py`, then
reformatted to match this project's established migration style and
verified with `alembic check` against a throwaway database.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "074a6657727b"
down_revision: str | None = "da8531b249c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column(
            "role",
            sa.Enum("OFFICER", "LAB_PERSONNEL", "ADMIN", name="userrole", native_enum=False),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)

    op.create_table(
        "user_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_sessions_token_hash"), "user_sessions", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)

    op.create_table(
        "custody_transfers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("evidence_id", sa.Integer(), nullable=False),
        sa.Column(
            "transfer_type",
            sa.Enum("INTAKE", "TRANSFER", name="custodytransfertype", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACCEPTED",
                "EXPIRED",
                "CANCELLED",
                "REJECTED",
                name="custodytransferstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("releasing_user_id", sa.Integer(), nullable=True),
        sa.Column("receiving_user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=True),
        sa.Column("initiated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("location", sa.String(length=256), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("provenance_event_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["provenance_event_id"], ["processing_events.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["receiving_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["releasing_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_custody_transfers_evidence_id"), "custody_transfers", ["evidence_id"], unique=False
    )
    op.create_index(
        op.f("ix_custody_transfers_receiving_user_id"),
        "custody_transfers",
        ["receiving_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_custody_transfers_releasing_user_id"),
        "custody_transfers",
        ["releasing_user_id"],
        unique=False,
    )
    # Partial unique index: at most one PENDING transfer per evidence
    # item, enforced by SQLite itself so a concurrent double-initiate
    # race cannot create two. See `app/models/custody.py`'s
    # `__table_args__` docstring for the full rationale.
    op.create_index(
        "ix_custody_transfers_one_pending_per_evidence",
        "custody_transfers",
        ["evidence_id"],
        unique=True,
        sqlite_where=sa.text("status = 'PENDING'"),
    )


def downgrade() -> None:
    op.drop_index("ix_custody_transfers_one_pending_per_evidence", table_name="custody_transfers")
    op.drop_index(op.f("ix_custody_transfers_releasing_user_id"), table_name="custody_transfers")
    op.drop_index(op.f("ix_custody_transfers_receiving_user_id"), table_name="custody_transfers")
    op.drop_index(op.f("ix_custody_transfers_evidence_id"), table_name="custody_transfers")
    op.drop_table("custody_transfers")

    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_token_hash"), table_name="user_sessions")
    op.drop_table("user_sessions")

    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
