"""phase_22_findings_notifications

Revision ID: 074c857a1285
Revises: 074a6657727b
Create Date: 2026-08-30 20:08:13.533145

Adds the two tables and one column Phase 22 ("Automatic Evidence
Processing, Findings & Officer Notifications") needs. None of this
touches any Phase 1-21 table's existing data -- `cases`, `evidence`,
`recordings`, `jobs`, `users` are read via foreign key only, and the new
`jobs.parent_job_id` column is nullable so every existing `Job` row
remains valid with no dependency parent.

- `findings` (`app/models/finding.py`): one review-level forensic finding
  surfaced by `app.core.processing_orchestrator.ProcessingOrchestrator` /
  `app.core.findings_engine.FindingsEngine`. `evidence_id`/`recording_id`
  use `ondelete='SET NULL'` (not `CASCADE`) -- task Phase 22 scope,
  "Finding Lifecycle": "Do not delete historical findings" -- a finding
  must outlive the evidence/recording row it was originally scoped to.
  `source_job_id` is `ondelete='SET NULL'` for the same reason.
- `notifications` (`app/models/notification.py`): one officer-facing
  pointer to a `Finding`. `ondelete='CASCADE'` on both `finding_id` and
  `recipient_user_id` -- a notification has no independent meaning once
  its finding is gone (there is none: findings are never deleted, only a
  hypothetical future data-retention purge would remove one) or once its
  recipient user account is gone.
- `jobs.parent_job_id` (`app/models/job.py`): self-referential, nullable
  foreign key forming the dependency tree the orchestrator builds
  between one root `job_type='orchestration'` run and the pipeline-stage
  jobs it schedules. Added via `batch_alter_table` (matching
  `bbf09bc1df18_corrective_case_evidence_cascade.py`'s established
  pattern) because SQLite cannot add a foreign key constraint to an
  existing table with a plain `ALTER TABLE`.

Autogenerated from `app/models/{finding,notification,job}.py` via
`alembic revision --autogenerate`, then hand-adjusted only for the
`jobs.parent_job_id` batch-mode requirement above; the `findings`/
`notifications` table bodies are unmodified from the autogenerated
output. Verified with `alembic upgrade head` / `alembic downgrade -1`
against a copy of the project's own development database.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "074c857a1285"
down_revision: str | None = "074a6657727b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_FK_JOBS_PARENT_JOB_ID = "fk_jobs_parent_job_id_jobs"


def upgrade() -> None:
    op.create_table(
        "findings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("evidence_id", sa.Integer(), nullable=True),
        sa.Column("recording_id", sa.Integer(), nullable=True),
        sa.Column("source_job_id", sa.Integer(), nullable=True),
        sa.Column("finding_type", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source_reference", sa.Text(), nullable=True),
        sa.Column("limitations", sa.Text(), nullable=True),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(length=256), nullable=True),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["recording_id"], ["recordings.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_findings_case_id"), "findings", ["case_id"], unique=False)
    op.create_index(op.f("ix_findings_evidence_id"), "findings", ["evidence_id"], unique=False)
    op.create_index(op.f("ix_findings_finding_type"), "findings", ["finding_type"], unique=False)
    op.create_index(op.f("ix_findings_recording_id"), "findings", ["recording_id"], unique=False)
    op.create_index(op.f("ix_findings_severity"), "findings", ["severity"], unique=False)
    op.create_index(
        op.f("ix_findings_source_job_id"), "findings", ["source_job_id"], unique=False
    )
    op.create_index(op.f("ix_findings_status"), "findings", ["status"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipient_user_id", sa.Integer(), nullable=False),
        sa.Column("finding_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["finding_id"], ["findings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recipient_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_finding_id"), "notifications", ["finding_id"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_recipient_user_id"),
        "notifications",
        ["recipient_user_id"],
        unique=False,
    )

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("parent_job_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            op.f("ix_jobs_parent_job_id"), ["parent_job_id"], unique=False
        )
        batch_op.create_foreign_key(
            _FK_JOBS_PARENT_JOB_ID, "jobs", ["parent_job_id"], ["id"], ondelete="CASCADE"
        )


def downgrade() -> None:
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_constraint(_FK_JOBS_PARENT_JOB_ID, type_="foreignkey")
        batch_op.drop_index(op.f("ix_jobs_parent_job_id"))
        batch_op.drop_column("parent_job_id")

    op.drop_index(op.f("ix_notifications_recipient_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_finding_id"), table_name="notifications")
    op.drop_table("notifications")

    op.drop_index(op.f("ix_findings_status"), table_name="findings")
    op.drop_index(op.f("ix_findings_source_job_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_severity"), table_name="findings")
    op.drop_index(op.f("ix_findings_recording_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_finding_type"), table_name="findings")
    op.drop_index(op.f("ix_findings_evidence_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_case_id"), table_name="findings")
    op.drop_table("findings")
