"""phase_3_evidence_hashing

Revision ID: 1e3e297f1687
Revises: bbf09bc1df18
Create Date: 2026-08-27 00:21:50.606998

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3e297f1687'
down_revision: str | None = 'bbf09bc1df18'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_hashes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.Enum('SHA256', 'MD5', name='hashalgorithm', native_enum=False), nullable=False),
    sa.Column('hash_value', sa.String(length=128), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('software_version', sa.String(length=32), nullable=True),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Enum('NOT_VERIFIED', 'VERIFIED', 'MISMATCH', name='verificationstatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id', 'algorithm', name='uq_evidence_hash_algorithm')
    )
    op.create_index(op.f('ix_evidence_hashes_evidence_id'), 'evidence_hashes', ['evidence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_hashes_evidence_id'), table_name='evidence_hashes')
    op.drop_table('evidence_hashes')
    # ### end Alembic commands ###