"""phase_2_core_domain_models

Revision ID: 2f5e9d71fc70
Revises: 3ef765197b2e
Create Date: 2026-08-26 22:54:37.572234

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f5e9d71fc70'
down_revision: str | None = '3ef765197b2e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('case_number', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('examiner', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PROCESSING', 'REVIEW', 'COMPLETED', 'ARCHIVED', name='casestatus', native_enum=False), nullable=False),
    sa.Column('software_version', sa.String(length=32), nullable=True),
    sa.Column('schema_version', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_id'), 'cases', ['case_id'], unique=True)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('source_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_id'), 'evidence', ['evidence_id'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('firmware', sa.String(length=128), nullable=True),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('device_type', sa.String(length=64), nullable=True),
    sa.Column('channel_count', sa.Integer(), nullable=True),
    sa.Column('camera_count', sa.Integer(), nullable=True),
    sa.Column('network_info', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('identification_method', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_evidence_id'), 'devices', ['evidence_id'], unique=True)
    op.create_table('recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.String(length=64), nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('start_original', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_original', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_normalized', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_normalized', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('codec', sa.String(length=64), nullable=True),
    sa.Column('container', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('source_location', sa.Text(), nullable=True),
    sa.Column('recovery_status', sa.String(length=64), nullable=True),
    sa.Column('recovery_method', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('artifact_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordings_camera_id'), 'recordings', ['camera_id'], unique=False)
    op.create_index(op.f('ix_recordings_evidence_id'), 'recordings', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_recordings_recording_id'), 'recordings', ['recording_id'], unique=True)
    op.create_table('storage_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('capacity_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sector_size', sa.Integer(), nullable=True),
    sa.Column('interface', sa.String(length=64), nullable=True),
    sa.Column('image_format', sa.String(length=64), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('read_only', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_devices_evidence_id'), 'storage_devices', ['evidence_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storage_devices_evidence_id'), table_name='storage_devices')
    op.drop_table('storage_devices')
    op.drop_index(op.f('ix_recordings_recording_id'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_evidence_id'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_camera_id'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_devices_evidence_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_evidence_evidence_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_cases_case_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###