"""phase_13_ai_analysis

Revision ID: 4e97650644e4
Revises: a1c4e8f26b73
Create Date: 2026-08-30 09:46:39.655949

Adds the four tables Phase 13 ("AI Analysis") needs and that did not exist
before it: `jobs` (Master Specification Section 48's generic job system --
none existed anywhere in this codebase prior to this migration), `ai_results`
(Section 50 already lists this table; this is the first migration to create
it), and `ai_tracks`/`motion_events` (new beyond Section 50's terse table
list, but directly justified by Section 32's "Tracking result" and Section
34's "Motion event" conceptual models -- the same terse-list-vs-richer-model
resolution already used for `recovery_results`/`timeline_events` in prior
phases). Autogenerated from the ORM models in `app/models/job.py` and
`app/models/ai_result.py`, then verified with `alembic check` against a
throwaway database.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e97650644e4"
down_revision: str | None = "a1c4e8f26b73"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("evidence_id", sa.Integer(), nullable=True),
        sa.Column("job_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("progress", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("worker", sa.String(length=64), nullable=True),
        sa.Column("recording_ids", sa.Text(), nullable=True),
        sa.Column("analysis_types", sa.Text(), nullable=True),
        sa.Column("model_versions", sa.Text(), nullable=True),
        sa.Column("parameters", sa.Text(), nullable=True),
        sa.Column("software_version", sa.String(length=32), nullable=True),
        sa.Column("results_count", sa.Integer(), nullable=False),
        sa.Column("input_artifacts", sa.Text(), nullable=True),
        sa.Column("output_artifacts", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("warnings", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_case_id"), "jobs", ["case_id"], unique=False)
    op.create_index(op.f("ix_jobs_evidence_id"), "jobs", ["evidence_id"], unique=False)
    op.create_index(op.f("ix_jobs_job_type"), "jobs", ["job_type"], unique=False)
    op.create_table(
        "ai_tracks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("recording_id", sa.Integer(), nullable=False),
        sa.Column("camera_id", sa.String(length=64), nullable=True),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("class_name", sa.String(length=64), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_seen_frame", sa.Integer(), nullable=False),
        sa.Column("last_seen_frame", sa.Integer(), nullable=False),
        sa.Column("trajectory", sa.Text(), nullable=True),
        sa.Column("frame_count", sa.Integer(), nullable=False),
        sa.Column("average_confidence", sa.Float(), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("tracker_version", sa.String(length=64), nullable=False),
        sa.Column("source_artifact", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recording_id"], ["recordings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_artifact"],
            ["artifacts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_tracks_camera_id"), "ai_tracks", ["camera_id"], unique=False)
    op.create_index(op.f("ix_ai_tracks_case_id"), "ai_tracks", ["case_id"], unique=False)
    op.create_index(op.f("ix_ai_tracks_job_id"), "ai_tracks", ["job_id"], unique=False)
    op.create_index(op.f("ix_ai_tracks_recording_id"), "ai_tracks", ["recording_id"], unique=False)
    op.create_index(
        op.f("ix_ai_tracks_source_artifact"), "ai_tracks", ["source_artifact"], unique=False
    )
    op.create_table(
        "motion_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("recording_id", sa.Integer(), nullable=False),
        sa.Column("camera_id", sa.String(length=64), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("regions", sa.Text(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("method", sa.String(length=64), nullable=False),
        sa.Column("parameters", sa.Text(), nullable=True),
        sa.Column("source_artifact", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recording_id"], ["recordings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_artifact"],
            ["artifacts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_motion_events_camera_id"), "motion_events", ["camera_id"], unique=False
    )
    op.create_index(op.f("ix_motion_events_case_id"), "motion_events", ["case_id"], unique=False)
    op.create_index(op.f("ix_motion_events_job_id"), "motion_events", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_motion_events_recording_id"), "motion_events", ["recording_id"], unique=False
    )
    op.create_index(
        op.f("ix_motion_events_source_artifact"), "motion_events", ["source_artifact"], unique=False
    )
    op.create_table(
        "ai_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("recording_id", sa.Integer(), nullable=False),
        sa.Column("analysis_type", sa.String(length=32), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("frame_number", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("class_name", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("bbox_x_min", sa.Float(), nullable=False),
        sa.Column("bbox_y_min", sa.Float(), nullable=False),
        sa.Column("bbox_x_max", sa.Float(), nullable=False),
        sa.Column("bbox_y_max", sa.Float(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=True),
        sa.Column("source_artifact", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recording_id"], ["recordings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_artifact"],
            ["artifacts.id"],
        ),
        sa.ForeignKeyConstraint(["track_id"], ["ai_tracks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_results_analysis_type"), "ai_results", ["analysis_type"], unique=False
    )
    op.create_index(op.f("ix_ai_results_case_id"), "ai_results", ["case_id"], unique=False)
    op.create_index(op.f("ix_ai_results_job_id"), "ai_results", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_ai_results_recording_id"), "ai_results", ["recording_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_results_source_artifact"), "ai_results", ["source_artifact"], unique=False
    )
    op.create_index(op.f("ix_ai_results_track_id"), "ai_results", ["track_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ai_results_track_id"), table_name="ai_results")
    op.drop_index(op.f("ix_ai_results_source_artifact"), table_name="ai_results")
    op.drop_index(op.f("ix_ai_results_recording_id"), table_name="ai_results")
    op.drop_index(op.f("ix_ai_results_job_id"), table_name="ai_results")
    op.drop_index(op.f("ix_ai_results_case_id"), table_name="ai_results")
    op.drop_index(op.f("ix_ai_results_analysis_type"), table_name="ai_results")
    op.drop_table("ai_results")
    op.drop_index(op.f("ix_motion_events_source_artifact"), table_name="motion_events")
    op.drop_index(op.f("ix_motion_events_recording_id"), table_name="motion_events")
    op.drop_index(op.f("ix_motion_events_job_id"), table_name="motion_events")
    op.drop_index(op.f("ix_motion_events_case_id"), table_name="motion_events")
    op.drop_index(op.f("ix_motion_events_camera_id"), table_name="motion_events")
    op.drop_table("motion_events")
    op.drop_index(op.f("ix_ai_tracks_source_artifact"), table_name="ai_tracks")
    op.drop_index(op.f("ix_ai_tracks_recording_id"), table_name="ai_tracks")
    op.drop_index(op.f("ix_ai_tracks_job_id"), table_name="ai_tracks")
    op.drop_index(op.f("ix_ai_tracks_case_id"), table_name="ai_tracks")
    op.drop_index(op.f("ix_ai_tracks_camera_id"), table_name="ai_tracks")
    op.drop_table("ai_tracks")
    op.drop_index(op.f("ix_jobs_job_type"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_evidence_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_case_id"), table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
