"""phase_14_validation_ground_truth

Revision ID: 4ff7f7a56474
Revises: 4e97650644e4
Create Date: 2026-08-30 10:22:31.954036

Adds the two tables Phase 14 ("Validation / Ground Truth") needs:
`ground_truth` (Master Specification Section 37's recovery-only test-case
model, generalized to also cover object/face/motion/track/correlation
ground truth per this phase's own broader scope -- the same terse-list-vs-
richer-model resolution already used for `recovery_results`/
`timeline_events`/`ai_results`) and `validation_metrics` (a flat,
per-named-metric table -- one row per precision/recall/F1/TP/FP/FN/etc.
a validation run produces, since these do not fit as fixed columns the
way Section 50's recovery-specific `validation_runs` table assumes).

Deliberately does NOT add a third "validation_runs"/"validation_jobs"
table: `jobs` (Phase 13) already is the generic run/job envelope this
phase reuses (`job_type="validation"`), per the task's own instruction not
to build a second job/metrics system where an existing one suffices.
Autogenerated from the ORM models in `app/models/validation.py`, then
verified with `alembic check` against a throwaway database.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4ff7f7a56474"
down_revision: str | None = "4e97650644e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ground_truth",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.String(length=128), nullable=False),
        sa.Column("recording_id", sa.Integer(), nullable=True),
        sa.Column("camera_id", sa.String(length=64), nullable=True),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("object_class", sa.String(length=64), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("frame_number", sa.Integer(), nullable=True),
        sa.Column("bbox_x_min", sa.Float(), nullable=True),
        sa.Column("bbox_y_min", sa.Float(), nullable=True),
        sa.Column("bbox_x_max", sa.Float(), nullable=True),
        sa.Column("bbox_y_max", sa.Float(), nullable=True),
        sa.Column("expected_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expected_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expected_duration_ms", sa.Integer(), nullable=True),
        sa.Column("expected_frames", sa.Integer(), nullable=True),
        sa.Column("expected_fragments", sa.Integer(), nullable=True),
        sa.Column("expected_hash", sa.String(length=64), nullable=True),
        sa.Column("group_reference", sa.String(length=128), nullable=True),
        sa.Column("source_reference", sa.String(length=256), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recording_id"], ["recordings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ground_truth_camera_id"), "ground_truth", ["camera_id"], unique=False)
    op.create_index(op.f("ix_ground_truth_case_id"), "ground_truth", ["case_id"], unique=False)
    op.create_index(
        op.f("ix_ground_truth_dataset_id"), "ground_truth", ["dataset_id"], unique=False
    )
    op.create_index(
        op.f("ix_ground_truth_event_type"), "ground_truth", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_ground_truth_group_reference"), "ground_truth", ["group_reference"], unique=False
    )
    op.create_index(
        op.f("ix_ground_truth_recording_id"), "ground_truth", ["recording_id"], unique=False
    )
    op.create_table(
        "validation_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.String(length=128), nullable=False),
        sa.Column("validation_type", sa.String(length=32), nullable=False),
        sa.Column("metric_name", sa.String(length=128), nullable=False),
        sa.Column("metric_value", sa.Float(), nullable=True),
        sa.Column("numerator", sa.Float(), nullable=True),
        sa.Column("denominator", sa.Float(), nullable=True),
        sa.Column("threshold", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_validation_metrics_case_id"), "validation_metrics", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_validation_metrics_dataset_id"), "validation_metrics", ["dataset_id"], unique=False
    )
    op.create_index(
        op.f("ix_validation_metrics_job_id"), "validation_metrics", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_validation_metrics_metric_name"),
        "validation_metrics",
        ["metric_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_validation_metrics_validation_type"),
        "validation_metrics",
        ["validation_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_validation_metrics_validation_type"), table_name="validation_metrics")
    op.drop_index(op.f("ix_validation_metrics_metric_name"), table_name="validation_metrics")
    op.drop_index(op.f("ix_validation_metrics_job_id"), table_name="validation_metrics")
    op.drop_index(op.f("ix_validation_metrics_dataset_id"), table_name="validation_metrics")
    op.drop_index(op.f("ix_validation_metrics_case_id"), table_name="validation_metrics")
    op.drop_table("validation_metrics")
    op.drop_index(op.f("ix_ground_truth_recording_id"), table_name="ground_truth")
    op.drop_index(op.f("ix_ground_truth_group_reference"), table_name="ground_truth")
    op.drop_index(op.f("ix_ground_truth_event_type"), table_name="ground_truth")
    op.drop_index(op.f("ix_ground_truth_dataset_id"), table_name="ground_truth")
    op.drop_index(op.f("ix_ground_truth_case_id"), table_name="ground_truth")
    op.drop_index(op.f("ix_ground_truth_camera_id"), table_name="ground_truth")
    op.drop_table("ground_truth")
    # ### end Alembic commands ###
