"""phase_4_artifacts

Revision ID: 554c260c0889
Revises: 1e3e297f1687
Create Date: 2026-08-27 16:35:52.729558

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '554c260c0889'
down_revision: str | None = '1e3e297f1687'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('parent_artifact_id', sa.Integer(), nullable=True),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=True),
    sa.Column('tool_version', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_artifact_id'], ['artifacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path', name='uq_artifact_path')
    )
    op.create_index(op.f('ix_artifacts_evidence_id'), 'artifacts', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_artifacts_parent_artifact_id'), 'artifacts', ['parent_artifact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifacts_parent_artifact_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_evidence_id'), table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###