"""phase_17_blockchain_anchors

Revision ID: 5a4d67f7d555
Revises: 5d25486b0700
Create Date: 2026-08-30 14:35:17.502677

Adds the one table Phase 17 ("Blockchain Anchoring") needs:
`blockchain_anchors`. Master Specification Section 50 documents this
table with eight fields: `id`, `case_id`, `audit_state_hash`, `network`,
`transaction_reference`, `created_at`, `status`, `verified_at`. Further
columns are added beyond that literal list, each required by a specific
task Phase 17 scope instruction rather than speculative -- see
`app/models/blockchain.py`'s module docstring for the full reasoning:

- `chain_id`: an explicit, deterministic ("case-{case_id}") chain
  identifier, traceable to the case and its Phase 16 audit chain (task
  Phase 17 scope section 4) -- the documented table is missing a field
  the narrative text explicitly requires.
- `provider`: which `BlockchainProvider` implementation produced this
  anchor (e.g. "local_testnet"), distinct from `network` (e.g. "local"),
  needed to resolve the correct provider again when verifying later
  (task Phase 17 scope section 5's allowance for "provider/network
  identification").
- `event_count`/`last_event_id`: NOT cosmetic -- required for
  verification to be correct at all. An anchor commits to "the chain
  through event `last_event_id`"; without pinning this, a later
  verification recomputing "the current full chain" would always find a
  spurious mismatch as soon as even one more (legitimate, untampered)
  event is appended after anchoring -- including the anchoring action's
  own recorded `ProcessingEvent` (task Phase 17 scope section 23).
- `reason`: the free-text label distinguishing why a given anchor was
  made (e.g. "periodic", "case_closure", "manual") -- supports recording
  more than one anchor per case, each independently retained (task
  Phase 17 scope section 11).
- `error`: failure detail when `status` is `"failed"` (task Phase 17
  scope section 5's explicit allowance for "error information").

No column on this table is ever rewritten after insert except
`verified_at` (`app.core.blockchain_manager.BlockchainManager.
verify_anchor`'s own bookkeeping about when an anchor was last checked)
-- every anchor, including superseded ones, is retained forever, never
replaced in place. Autogenerated from `app/models/blockchain.py`, then
verified with `alembic check` against a throwaway database.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a4d67f7d555"
down_revision: str | None = "5d25486b0700"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blockchain_anchors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("chain_id", sa.String(length=128), nullable=False),
        sa.Column("audit_state_hash", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("network", sa.String(length=64), nullable=False),
        sa.Column("transaction_reference", sa.String(length=256), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("event_count", sa.Integer(), nullable=False),
        sa.Column("last_event_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_blockchain_anchors_case_id"), "blockchain_anchors", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_blockchain_anchors_chain_id"), "blockchain_anchors", ["chain_id"], unique=False
    )
    op.create_index(
        op.f("ix_blockchain_anchors_transaction_reference"),
        "blockchain_anchors",
        ["transaction_reference"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_blockchain_anchors_transaction_reference"), table_name="blockchain_anchors"
    )
    op.drop_index(op.f("ix_blockchain_anchors_chain_id"), table_name="blockchain_anchors")
    op.drop_index(op.f("ix_blockchain_anchors_case_id"), table_name="blockchain_anchors")
    op.drop_table("blockchain_anchors")
    # ### end Alembic commands ###
