"""phase_15_processing_events

Revision ID: 5d25486b0700
Revises: 4ff7f7a56474
Create Date: 2026-08-30 10:52:23.323225

Adds the one table Phase 15 ("Provenance / Chain of Custody") needs:
`processing_events`. Master Specification Section 50 documents two
overlapping terse tables (`provenance_events` and `custody_events`) that
describe nearly the same shape twice; this migration merges both into the
task's own explicitly requested "one coherent typed processing-event
concept" (the same terse-list-vs-richer-model resolution already used for
`recovery_results`/`timeline_events`/`ai_results`/`ground_truth`).

No artifact-lineage table is added: `Artifact.parent_artifact_id` (Phase
4) plus `Artifact.evidence_id` already provide full artifact-to-artifact
and artifact-to-evidence traceability -- confirmed by inspection that
`RecordingManager.extract_recording` (Phase 9) already sets
`parent_artifact_id` when registering derived artifacts.

`previous_hash`/`current_hash` are the exact columns Section 50 documents
on both source tables; they exist here but stay `NULL` in every row this
phase writes -- Phase 16 (`app.audit.hash_chain`, still an empty stub) is
the phase that computes and populates them. Autogenerated from
`app/models/audit.py`, then verified with `alembic check` against a
throwaway database.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d25486b0700"
down_revision: str | None = "4ff7f7a56474"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processing_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("evidence_id", sa.Integer(), nullable=True),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=256), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("tool", sa.String(length=128), nullable=True),
        sa.Column("tool_version", sa.String(length=64), nullable=True),
        sa.Column("software_version", sa.String(length=32), nullable=True),
        sa.Column("parameters", sa.Text(), nullable=True),
        sa.Column("input_artifact_ids", sa.Text(), nullable=True),
        sa.Column("output_artifact_ids", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("warnings", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location_reference", sa.String(length=256), nullable=True),
        sa.Column("previous_hash", sa.String(length=64), nullable=True),
        sa.Column("current_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_processing_events_case_id"), "processing_events", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_processing_events_evidence_id"), "processing_events", ["evidence_id"], unique=False
    )
    op.create_index(
        op.f("ix_processing_events_job_id"), "processing_events", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_processing_events_operation"), "processing_events", ["operation"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_processing_events_operation"), table_name="processing_events")
    op.drop_index(op.f("ix_processing_events_job_id"), table_name="processing_events")
    op.drop_index(op.f("ix_processing_events_evidence_id"), table_name="processing_events")
    op.drop_index(op.f("ix_processing_events_case_id"), table_name="processing_events")
    op.drop_table("processing_events")
    # ### end Alembic commands ###
