"""phase_25_case_user_access

Revision ID: d886e2345a1b
Revises: fc43eac2e8d1
Create Date: 2026-08-31 21:02:26.546463

Adds `case_user_access` (`app.models.case_access.CaseUserAccess`): one row
per (user, case) access grant, enforced by `app.core.
case_authorization_service.CaseAuthorizationService` and the
`app.api.deps.require_case_access*` FastAPI dependencies built on it
(Phase 25, "Case-Level Access Control / Admin Permission Matrix").

A brand-new table with plain FKs to already-existing `cases`/`users` --
no `batch_alter_table` needed (unlike `074c857a1285`'s `jobs.
parent_job_id`, which added a FK column to an existing table): this
migration only ever `CREATE TABLE`s.

Autogenerated via `alembic revision --autogenerate`, unmodified except
for this docstring and formatting. Verified with `alembic upgrade head` /
`alembic downgrade -1` against a copy of the project's own development
database, and `alembic check`.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d886e2345a1b"
down_revision: str | None = "fc43eac2e8d1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "case_user_access",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "REVOKED", name="caseaccessstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("granted_by_user_id", sa.Integer(), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by_user_id", sa.Integer(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["granted_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["revoked_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "case_id", name="uq_case_user_access_user_case"),
    )
    op.create_index(
        op.f("ix_case_user_access_case_id"), "case_user_access", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_case_user_access_status"), "case_user_access", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_case_user_access_user_id"), "case_user_access", ["user_id"], unique=False
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_case_user_access_user_id"), table_name="case_user_access")
    op.drop_index(op.f("ix_case_user_access_status"), table_name="case_user_access")
    op.drop_index(op.f("ix_case_user_access_case_id"), table_name="case_user_access")
    op.drop_table("case_user_access")
