"""phase_18_reports

Revision ID: da8531b249c6
Revises: 5a4d67f7d555
Create Date: 2026-08-30 15:08:30.086720

Adds the one table Phase 18 ("Standardized Reporting") needs: `reports`.
Master Specification Section 50 documents this table with eight fields:
`id`, `case_id`, `report_type`, `path`, `created_at`, `software_version`,
`report_hash`, `status`. Further columns are added beyond that literal
list, each required by a specific task Phase 18 scope instruction rather
than speculative -- see `app/models/report.py`'s module docstring for the
full reasoning:

- `report_type` (the doc's own column name) is repurposed to store this
  row's file *format* (`"json"`/`"pdf"`) -- Phase 18 implements one
  report content, rendered in two formats, so "type" and "format"
  collapse to the same value; one row always represents exactly one
  generated file, matching the doc's one-`path`/one-`report_hash` shape
  directly rather than inventing a "one row, two files" schema.
- `job_id`: links back to the `Job` that produced this row (task Phase
  18 scope section 23 -- reusing the existing job system, mirroring
  `AIResult.job_id`/`ValidationMetric.job_id`).
- `report_schema_version`: task Phase 18 scope section 4 requires
  keeping the report *schema* version explicitly distinct from
  `software_version`.
- `completed_at`: when generation of this specific file finished,
  distinct from `created_at` -- mirrors `Job.started_at`/`completed_at`.
- `error`/`warnings`: task Phase 18 scope section 5's "error
  information" and the general warnings-field convention already used
  by `ProcessingEvent`/`Job`/other persisted results.

Does not store the complete report body (task Phase 18 scope section 26)
-- only the file path and its hash; the file itself lives under
`REPORT_ROOT`, never inside the preserved evidence root. Autogenerated
from `app/models/report.py`, then verified with `alembic check` against
a throwaway database.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da8531b249c6"
down_revision: str | None = "5a4d67f7d555"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("report_type", sa.String(length=16), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("report_hash", sa.String(length=64), nullable=True),
        sa.Column("report_schema_version", sa.String(length=32), nullable=False),
        sa.Column("software_version", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("warnings", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reports_case_id"), "reports", ["case_id"], unique=False)
    op.create_index(op.f("ix_reports_job_id"), "reports", ["job_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reports_job_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_case_id"), table_name="reports")
    op.drop_table("reports")
    # ### end Alembic commands ###
