"""phase_24_job_resource_metrics

Revision ID: fc43eac2e8d1
Revises: 074c857a1285
Create Date: 2026-08-31 14:10:58.702054

Adds `jobs.resource_metrics` (nullable `TEXT`, JSON-encoded): real,
measured per-job resource usage (`app.core.resource_metrics`) --
high-resolution runtime, CPU seconds, and RSS deltas captured directly
from the OS around `ProcessingOrchestrator`'s pipeline-stage jobs, never
estimated or manually entered. `NULL` for every existing row and every
job type that does not populate it -- purely additive, no backfill.

A plain nullable column addition (no foreign key), so unlike
`074c857a1285`'s `jobs.parent_job_id` this does not need
`batch_alter_table` on SQLite.

Autogenerated via `alembic revision --autogenerate`, unmodified except
for this docstring. Verified with `alembic upgrade head` / `alembic
downgrade -1` against a copy of the project's own development database.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc43eac2e8d1"
down_revision: str | None = "074c857a1285"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("jobs", sa.Column("resource_metrics", sa.Text(), nullable=True))


def downgrade() -> None:
    op.drop_column("jobs", "resource_metrics")
